# Configuration for Spring Filter Wheel

# Web interface connection settings
web_interface:
  base_url: "http://192.168.1.228:5001"
  request_timeout: 10  # seconds

# Filter positions
filters:
  positions: [0, 1, 2, 3, 4, 5, 6]
  dark_filter: 6  # which filter position is the dark filter (will close shutter)
  names:
    0: "u"
    1: "g"
    2: "r"
    3: "i"
    4: "Y"
    5: "J"
    6: "empty"

# Timing settings
state_update_dt: 0.5  # seconds between status polls during moves
timeout_secs: 60  # maximum time to wait for a move to complete

# where to put the log. base directory is home
log_directory: 'data/log'
log_link_directory: 'data'
log_link_name: 'winter.log'